name: Build and Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Find solution file
        id: find_sln
        run: echo "SOLUTION_PATH=$(find $GITHUB_WORKSPACE -name '*.sln' | head -n 1)" >> $GITHUB_ENV

      - name: Display solution path
        run: echo ${{ env.SOLUTION_PATH }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build "${{ env.SOLUTION_PATH }}" --no-restore

      - name: Test
        run: dotnet test "${{ env.SOLUTION_PATH }}" --no-build --verbosity normal

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            **/bin/**
            **/obj/**

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./TestResults/

