name: Code Analysis

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout full repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Find solution file
        id: find_sln
        run: echo "SOLUTION_PATH=$(find $GITHUB_WORKSPACE -name '*.sln' | head -n 1)" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Run .NET Code Analysis
        run: dotnet build "${{ env.SOLUTION_PATH }}" /p:TreatWarningsAsErrors=true

      - name: Upload Analysis Report
        uses: actions/upload-artifact@v3
        with:
          name: code-analysis-report
          path: ./AnalysisReports/
