name: OWASP Dependency Check

on:
  workflow_run:
    workflows: ["CodeQL"]
    types:
      - completed
  pull_request:
    branches: [ "*" ] 

jobs:
  owasp-dependency-check:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout full repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "DeveloperEvaluation"
          path: "src"
          format: "HTML"
          out: "dependency-check-report"

      - name: Upload OWASP Report
        uses: actions/upload-artifact@v3
        with:
          name: owasp-report
          path: dependency-check-report/
