name: Publish

on:
  workflow_run:
    workflows: ["OWASP Dependency Check"]
    types:
      - completed
  pull_request:
    branches: [ "*" ] 

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout full repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Find solution file
        id: find_sln
        run: echo "SOLUTION_PATH=$(find $GITHUB_WORKSPACE -name '*.sln' | head -n 1)" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Publish
        run: dotnet publish "${{ github.workspace }}/src/DeveloperEvaluation.WebApi/DeveloperEvaluation.WebApi.csproj" -c Release -o ./publish

      - name: Create ZIP file
        run: zip -r ./output.zip ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./output.zip
