jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout full repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Debug File Structure
      run: ls -R src/

    - name: Check DeveloperEvaluation.Domain.csproj
      run: test -f src/DeveloperEvaluation.Domain/DeveloperEvaluation.Domain.csproj && echo "File Exists" || echo "File Not Found"

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build --no-restore

    - name: Build DeveloperEvaluation.Domain separately (if needed)
      run: dotnet build src/DeveloperEvaluation.Domain/DeveloperEvaluation.Domain.csproj --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish Web API
      run: dotnet publish src/DeveloperEvaluation.WebApi/DeveloperEvaluation.WebApi.csproj -c Release -o ./publish

    - name: Create ZIP file
      run: zip -r ./output.zip ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: ./output.zip
