name: .NET Build & Test

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all files are downloaded

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Debug: Show Current Directory
        run: pwd

      - name: Debug: List All Files
        run: ls -R ${{ github.workspace }}

      - name: Debug: Check for .csproj Files
        run: find ${{ github.workspace }}/src -name "*.csproj"

      - name: Set Solution Path
        run: echo "SOLUTION_PATH=${{ github.workspace }}/DeveloperEvaluation.sln" >> $GITHUB_ENV

      - name: Display Solution Path
        run: cat $GITHUB_ENV

      - name: Restore Dependencies
        run: dotnet restore "${{ env.SOLUTION_PATH }}"

      - name: Build Solution
        run: dotnet build "${{ env.SOLUTION_PATH }}" --no-restore

      - name: Run Tests
        run: dotnet test "${{ env.SOLUTION_PATH }}" --no-build --verbosity normal

      - name: Publish Web API
        run: dotnet publish src/DeveloperEvaluation.WebApi/DeveloperEvaluation.WebApi.csproj -c Release -o ./publish

      - name: Package Build Artifacts
        run: zip -r ./output.zip ./publish

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./output.zip
